// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.12.4
// source: stock/v1/stock.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationStockServiceAddStockPrice = "/stock.v1.StockService/AddStockPrice"
const OperationStockServiceGetStockList = "/stock.v1.StockService/GetStockList"

type StockServiceHTTPServer interface {
	// AddStockPrice
	AddStockPrice(context.Context, *StockPriceRequest) (*StockPriceReply, error)
	// GetStockList 查询股票列表
	GetStockList(context.Context, *StockInfoRequest) (*StockInfoReply, error)
}

func RegisterStockServiceHTTPServer(s *http.Server, srv StockServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/stock", _StockService_GetStockList0_HTTP_Handler(srv))
	r.POST("/api/stock/price", _StockService_AddStockPrice0_HTTP_Handler(srv))
}

func _StockService_GetStockList0_HTTP_Handler(srv StockServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StockInfoRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStockServiceGetStockList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStockList(ctx, req.(*StockInfoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StockInfoReply)
		return ctx.Result(200, reply)
	}
}

func _StockService_AddStockPrice0_HTTP_Handler(srv StockServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StockPriceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStockServiceAddStockPrice)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddStockPrice(ctx, req.(*StockPriceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StockPriceReply)
		return ctx.Result(200, reply)
	}
}

type StockServiceHTTPClient interface {
	// AddStockPrice
	AddStockPrice(ctx context.Context, req *StockPriceRequest, opts ...http.CallOption) (rsp *StockPriceReply, err error)
	// GetStockList 查询股票列表
	GetStockList(ctx context.Context, req *StockInfoRequest, opts ...http.CallOption) (rsp *StockInfoReply, err error)
}

type StockServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewStockServiceHTTPClient(client *http.Client) StockServiceHTTPClient {
	return &StockServiceHTTPClientImpl{client}
}

// AddStockPrice
func (c *StockServiceHTTPClientImpl) AddStockPrice(ctx context.Context, in *StockPriceRequest, opts ...http.CallOption) (*StockPriceReply, error) {
	var out StockPriceReply
	pattern := "/api/stock/price"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStockServiceAddStockPrice))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetStockList 查询股票列表
func (c *StockServiceHTTPClientImpl) GetStockList(ctx context.Context, in *StockInfoRequest, opts ...http.CallOption) (*StockInfoReply, error) {
	var out StockInfoReply
	pattern := "/api/stock"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStockServiceGetStockList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
