// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: stock/v1/stock.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateStockPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockPriceRequest) Reset() {
	*x = UpdateStockPriceRequest{}
	mi := &file_stock_v1_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockPriceRequest) ProtoMessage() {}

func (x *UpdateStockPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_v1_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockPriceRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockPriceRequest) Descriptor() ([]byte, []int) {
	return file_stock_v1_stock_proto_rawDescGZIP(), []int{0}
}

type UpdateStockPriceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockPriceReply) Reset() {
	*x = UpdateStockPriceReply{}
	mi := &file_stock_v1_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockPriceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockPriceReply) ProtoMessage() {}

func (x *UpdateStockPriceReply) ProtoReflect() protoreflect.Message {
	mi := &file_stock_v1_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockPriceReply.ProtoReflect.Descriptor instead.
func (*UpdateStockPriceReply) Descriptor() ([]byte, []int) {
	return file_stock_v1_stock_proto_rawDescGZIP(), []int{1}
}

type InitStockInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitStockInfoRequest) Reset() {
	*x = InitStockInfoRequest{}
	mi := &file_stock_v1_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitStockInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitStockInfoRequest) ProtoMessage() {}

func (x *InitStockInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_v1_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitStockInfoRequest.ProtoReflect.Descriptor instead.
func (*InitStockInfoRequest) Descriptor() ([]byte, []int) {
	return file_stock_v1_stock_proto_rawDescGZIP(), []int{2}
}

type InitStockInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitStockInfoReply) Reset() {
	*x = InitStockInfoReply{}
	mi := &file_stock_v1_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitStockInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitStockInfoReply) ProtoMessage() {}

func (x *InitStockInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_stock_v1_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitStockInfoReply.ProtoReflect.Descriptor instead.
func (*InitStockInfoReply) Descriptor() ([]byte, []int) {
	return file_stock_v1_stock_proto_rawDescGZIP(), []int{3}
}

type StockInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockCode     string                 `protobuf:"bytes,1,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"`
	StockName     string                 `protobuf:"bytes,2,opt,name=stock_name,json=stockName,proto3" json:"stock_name,omitempty"`
	StockType     string                 `protobuf:"bytes,3,opt,name=stock_type,json=stockType,proto3" json:"stock_type,omitempty"`
	StockMarket   string                 `protobuf:"bytes,4,opt,name=stock_market,json=stockMarket,proto3" json:"stock_market,omitempty"`
	Id            int64                  `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockInfoRequest) Reset() {
	*x = StockInfoRequest{}
	mi := &file_stock_v1_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockInfoRequest) ProtoMessage() {}

func (x *StockInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_v1_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockInfoRequest.ProtoReflect.Descriptor instead.
func (*StockInfoRequest) Descriptor() ([]byte, []int) {
	return file_stock_v1_stock_proto_rawDescGZIP(), []int{4}
}

func (x *StockInfoRequest) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

func (x *StockInfoRequest) GetStockName() string {
	if x != nil {
		return x.StockName
	}
	return ""
}

func (x *StockInfoRequest) GetStockType() string {
	if x != nil {
		return x.StockType
	}
	return ""
}

func (x *StockInfoRequest) GetStockMarket() string {
	if x != nil {
		return x.StockMarket
	}
	return ""
}

func (x *StockInfoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StockInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stocks        []*StockInfo           `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockInfoReply) Reset() {
	*x = StockInfoReply{}
	mi := &file_stock_v1_stock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockInfoReply) ProtoMessage() {}

func (x *StockInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_stock_v1_stock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockInfoReply.ProtoReflect.Descriptor instead.
func (*StockInfoReply) Descriptor() ([]byte, []int) {
	return file_stock_v1_stock_proto_rawDescGZIP(), []int{5}
}

func (x *StockInfoReply) GetStocks() []*StockInfo {
	if x != nil {
		return x.Stocks
	}
	return nil
}

type StockInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockCode     string                 `protobuf:"bytes,1,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"`
	StockName     string                 `protobuf:"bytes,2,opt,name=stock_name,json=stockName,proto3" json:"stock_name,omitempty"`
	StockType     string                 `protobuf:"bytes,3,opt,name=stock_type,json=stockType,proto3" json:"stock_type,omitempty"`
	StockMarket   string                 `protobuf:"bytes,4,opt,name=stock_market,json=stockMarket,proto3" json:"stock_market,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockInfo) Reset() {
	*x = StockInfo{}
	mi := &file_stock_v1_stock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockInfo) ProtoMessage() {}

func (x *StockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stock_v1_stock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockInfo.ProtoReflect.Descriptor instead.
func (*StockInfo) Descriptor() ([]byte, []int) {
	return file_stock_v1_stock_proto_rawDescGZIP(), []int{6}
}

func (x *StockInfo) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

func (x *StockInfo) GetStockName() string {
	if x != nil {
		return x.StockName
	}
	return ""
}

func (x *StockInfo) GetStockType() string {
	if x != nil {
		return x.StockType
	}
	return ""
}

func (x *StockInfo) GetStockMarket() string {
	if x != nil {
		return x.StockMarket
	}
	return ""
}

type StockPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockId       string                 `protobuf:"bytes,1,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`                      // 股票代码
	TradeDate     string                 `protobuf:"bytes,2,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"`                // 交易日期
	OpenPrice     float64                `protobuf:"fixed64,3,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`              // 开盘价
	ClosePrice    float64                `protobuf:"fixed64,4,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"`           // 收盘价
	HighPrice     float64                `protobuf:"fixed64,5,opt,name=high_price,json=highPrice,proto3" json:"high_price,omitempty"`              // 最高价
	LowPrice      float64                `protobuf:"fixed64,6,opt,name=low_price,json=lowPrice,proto3" json:"low_price,omitempty"`                 // 最低价
	Volume        int64                  `protobuf:"varint,7,opt,name=volume,proto3" json:"volume,omitempty"`                                      // 成交量
	Amount        float64                `protobuf:"fixed64,8,opt,name=amount,proto3" json:"amount,omitempty"`                                     // 成交额
	ChangePercent float64                `protobuf:"fixed64,9,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`  // 涨跌幅(%)
	MarginBalance float64                `protobuf:"fixed64,10,opt,name=margin_balance,json=marginBalance,proto3" json:"margin_balance,omitempty"` // 融资融券余额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockPriceRequest) Reset() {
	*x = StockPriceRequest{}
	mi := &file_stock_v1_stock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockPriceRequest) ProtoMessage() {}

func (x *StockPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_v1_stock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockPriceRequest.ProtoReflect.Descriptor instead.
func (*StockPriceRequest) Descriptor() ([]byte, []int) {
	return file_stock_v1_stock_proto_rawDescGZIP(), []int{7}
}

func (x *StockPriceRequest) GetStockId() string {
	if x != nil {
		return x.StockId
	}
	return ""
}

func (x *StockPriceRequest) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

func (x *StockPriceRequest) GetOpenPrice() float64 {
	if x != nil {
		return x.OpenPrice
	}
	return 0
}

func (x *StockPriceRequest) GetClosePrice() float64 {
	if x != nil {
		return x.ClosePrice
	}
	return 0
}

func (x *StockPriceRequest) GetHighPrice() float64 {
	if x != nil {
		return x.HighPrice
	}
	return 0
}

func (x *StockPriceRequest) GetLowPrice() float64 {
	if x != nil {
		return x.LowPrice
	}
	return 0
}

func (x *StockPriceRequest) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *StockPriceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StockPriceRequest) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *StockPriceRequest) GetMarginBalance() float64 {
	if x != nil {
		return x.MarginBalance
	}
	return 0
}

type StockPriceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockPriceReply) Reset() {
	*x = StockPriceReply{}
	mi := &file_stock_v1_stock_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockPriceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockPriceReply) ProtoMessage() {}

func (x *StockPriceReply) ProtoReflect() protoreflect.Message {
	mi := &file_stock_v1_stock_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockPriceReply.ProtoReflect.Descriptor instead.
func (*StockPriceReply) Descriptor() ([]byte, []int) {
	return file_stock_v1_stock_proto_rawDescGZIP(), []int{8}
}

var File_stock_v1_stock_proto protoreflect.FileDescriptor

const file_stock_v1_stock_proto_rawDesc = "" +
	"\n" +
	"\x14stock/v1/stock.proto\x12\bstock.v1\x1a\x1cgoogle/api/annotations.proto\"\x19\n" +
	"\x17UpdateStockPriceRequest\"\x17\n" +
	"\x15UpdateStockPriceReply\"\x16\n" +
	"\x14InitStockInfoRequest\"\x14\n" +
	"\x12InitStockInfoReply\"\xa2\x01\n" +
	"\x10StockInfoRequest\x12\x1d\n" +
	"\n" +
	"stock_code\x18\x01 \x01(\tR\tstockCode\x12\x1d\n" +
	"\n" +
	"stock_name\x18\x02 \x01(\tR\tstockName\x12\x1d\n" +
	"\n" +
	"stock_type\x18\x03 \x01(\tR\tstockType\x12!\n" +
	"\fstock_market\x18\x04 \x01(\tR\vstockMarket\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\x03R\x02id\"=\n" +
	"\x0eStockInfoReply\x12+\n" +
	"\x06stocks\x18\x01 \x03(\v2\x13.stock.v1.StockInfoR\x06stocks\"\x8b\x01\n" +
	"\tStockInfo\x12\x1d\n" +
	"\n" +
	"stock_code\x18\x01 \x01(\tR\tstockCode\x12\x1d\n" +
	"\n" +
	"stock_name\x18\x02 \x01(\tR\tstockName\x12\x1d\n" +
	"\n" +
	"stock_type\x18\x03 \x01(\tR\tstockType\x12!\n" +
	"\fstock_market\x18\x04 \x01(\tR\vstockMarket\"\xc7\x02\n" +
	"\x11StockPriceRequest\x12\x19\n" +
	"\bstock_id\x18\x01 \x01(\tR\astockId\x12\x1d\n" +
	"\n" +
	"trade_date\x18\x02 \x01(\tR\ttradeDate\x12\x1d\n" +
	"\n" +
	"open_price\x18\x03 \x01(\x01R\topenPrice\x12\x1f\n" +
	"\vclose_price\x18\x04 \x01(\x01R\n" +
	"closePrice\x12\x1d\n" +
	"\n" +
	"high_price\x18\x05 \x01(\x01R\thighPrice\x12\x1b\n" +
	"\tlow_price\x18\x06 \x01(\x01R\blowPrice\x12\x16\n" +
	"\x06volume\x18\a \x01(\x03R\x06volume\x12\x16\n" +
	"\x06amount\x18\b \x01(\x01R\x06amount\x12%\n" +
	"\x0echange_percent\x18\t \x01(\x01R\rchangePercent\x12%\n" +
	"\x0emargin_balance\x18\n" +
	" \x01(\x01R\rmarginBalance\"\x11\n" +
	"\x0fStockPriceReply2\xc4\x03\n" +
	"\fStockService\x12^\n" +
	"\fGetStockList\x12\x1a.stock.v1.StockInfoRequest\x1a\x18.stock.v1.StockInfoReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/stock\x12g\n" +
	"\rAddStockPrice\x12\x1b.stock.v1.StockPriceRequest\x1a\x19.stock.v1.StockPriceReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/stock/price\x12l\n" +
	"\rInitStockInfo\x12\x1e.stock.v1.InitStockInfoRequest\x1a\x1c.stock.v1.InitStockInfoReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/stock/init\x12}\n" +
	"\x10UpdateStockPrice\x12!.stock.v1.UpdateStockPriceRequest\x1a\x1f.stock.v1.UpdateStockPriceReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/stock/price/updateBE\n" +
	"\x17dev.kratos.api.stock.v1B\fStockProtoV1P\x01Z\x1astock_info/api/stock/v1;v1b\x06proto3"

var (
	file_stock_v1_stock_proto_rawDescOnce sync.Once
	file_stock_v1_stock_proto_rawDescData []byte
)

func file_stock_v1_stock_proto_rawDescGZIP() []byte {
	file_stock_v1_stock_proto_rawDescOnce.Do(func() {
		file_stock_v1_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stock_v1_stock_proto_rawDesc), len(file_stock_v1_stock_proto_rawDesc)))
	})
	return file_stock_v1_stock_proto_rawDescData
}

var file_stock_v1_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_stock_v1_stock_proto_goTypes = []any{
	(*UpdateStockPriceRequest)(nil), // 0: stock.v1.UpdateStockPriceRequest
	(*UpdateStockPriceReply)(nil),   // 1: stock.v1.UpdateStockPriceReply
	(*InitStockInfoRequest)(nil),    // 2: stock.v1.InitStockInfoRequest
	(*InitStockInfoReply)(nil),      // 3: stock.v1.InitStockInfoReply
	(*StockInfoRequest)(nil),        // 4: stock.v1.StockInfoRequest
	(*StockInfoReply)(nil),          // 5: stock.v1.StockInfoReply
	(*StockInfo)(nil),               // 6: stock.v1.StockInfo
	(*StockPriceRequest)(nil),       // 7: stock.v1.StockPriceRequest
	(*StockPriceReply)(nil),         // 8: stock.v1.StockPriceReply
}
var file_stock_v1_stock_proto_depIdxs = []int32{
	6, // 0: stock.v1.StockInfoReply.stocks:type_name -> stock.v1.StockInfo
	4, // 1: stock.v1.StockService.GetStockList:input_type -> stock.v1.StockInfoRequest
	7, // 2: stock.v1.StockService.AddStockPrice:input_type -> stock.v1.StockPriceRequest
	2, // 3: stock.v1.StockService.InitStockInfo:input_type -> stock.v1.InitStockInfoRequest
	0, // 4: stock.v1.StockService.UpdateStockPrice:input_type -> stock.v1.UpdateStockPriceRequest
	5, // 5: stock.v1.StockService.GetStockList:output_type -> stock.v1.StockInfoReply
	8, // 6: stock.v1.StockService.AddStockPrice:output_type -> stock.v1.StockPriceReply
	3, // 7: stock.v1.StockService.InitStockInfo:output_type -> stock.v1.InitStockInfoReply
	1, // 8: stock.v1.StockService.UpdateStockPrice:output_type -> stock.v1.UpdateStockPriceReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stock_v1_stock_proto_init() }
func file_stock_v1_stock_proto_init() {
	if File_stock_v1_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stock_v1_stock_proto_rawDesc), len(file_stock_v1_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stock_v1_stock_proto_goTypes,
		DependencyIndexes: file_stock_v1_stock_proto_depIdxs,
		MessageInfos:      file_stock_v1_stock_proto_msgTypes,
	}.Build()
	File_stock_v1_stock_proto = out.File
	file_stock_v1_stock_proto_goTypes = nil
	file_stock_v1_stock_proto_depIdxs = nil
}
