// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: stock/v1/stock.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StockService_GetStockList_FullMethodName     = "/stock.v1.StockService/GetStockList"
	StockService_AddStockPrice_FullMethodName    = "/stock.v1.StockService/AddStockPrice"
	StockService_InitStockInfo_FullMethodName    = "/stock.v1.StockService/InitStockInfo"
	StockService_UpdateStockPrice_FullMethodName = "/stock.v1.StockService/UpdateStockPrice"
)

// StockServiceClient is the client API for StockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type StockServiceClient interface {
	// 查询股票列表
	GetStockList(ctx context.Context, in *StockInfoRequest, opts ...grpc.CallOption) (*StockInfoReply, error)
	// 增加股票价格信息
	AddStockPrice(ctx context.Context, in *StockPriceRequest, opts ...grpc.CallOption) (*StockPriceReply, error)
	// 初始化股票信息
	InitStockInfo(ctx context.Context, in *InitStockInfoRequest, opts ...grpc.CallOption) (*InitStockInfoReply, error)
	UpdateStockPrice(ctx context.Context, in *UpdateStockPriceRequest, opts ...grpc.CallOption) (*UpdateStockPriceReply, error)
}

type stockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStockServiceClient(cc grpc.ClientConnInterface) StockServiceClient {
	return &stockServiceClient{cc}
}

func (c *stockServiceClient) GetStockList(ctx context.Context, in *StockInfoRequest, opts ...grpc.CallOption) (*StockInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockInfoReply)
	err := c.cc.Invoke(ctx, StockService_GetStockList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) AddStockPrice(ctx context.Context, in *StockPriceRequest, opts ...grpc.CallOption) (*StockPriceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockPriceReply)
	err := c.cc.Invoke(ctx, StockService_AddStockPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) InitStockInfo(ctx context.Context, in *InitStockInfoRequest, opts ...grpc.CallOption) (*InitStockInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitStockInfoReply)
	err := c.cc.Invoke(ctx, StockService_InitStockInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) UpdateStockPrice(ctx context.Context, in *UpdateStockPriceRequest, opts ...grpc.CallOption) (*UpdateStockPriceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStockPriceReply)
	err := c.cc.Invoke(ctx, StockService_UpdateStockPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockServiceServer is the server API for StockService service.
// All implementations must embed UnimplementedStockServiceServer
// for forward compatibility.
//
// The greeting service definition.
type StockServiceServer interface {
	// 查询股票列表
	GetStockList(context.Context, *StockInfoRequest) (*StockInfoReply, error)
	// 增加股票价格信息
	AddStockPrice(context.Context, *StockPriceRequest) (*StockPriceReply, error)
	// 初始化股票信息
	InitStockInfo(context.Context, *InitStockInfoRequest) (*InitStockInfoReply, error)
	UpdateStockPrice(context.Context, *UpdateStockPriceRequest) (*UpdateStockPriceReply, error)
	mustEmbedUnimplementedStockServiceServer()
}

// UnimplementedStockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStockServiceServer struct{}

func (UnimplementedStockServiceServer) GetStockList(context.Context, *StockInfoRequest) (*StockInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStockList not implemented")
}
func (UnimplementedStockServiceServer) AddStockPrice(context.Context, *StockPriceRequest) (*StockPriceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AddStockPrice not implemented")
}
func (UnimplementedStockServiceServer) InitStockInfo(context.Context, *InitStockInfoRequest) (*InitStockInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method InitStockInfo not implemented")
}
func (UnimplementedStockServiceServer) UpdateStockPrice(context.Context, *UpdateStockPriceRequest) (*UpdateStockPriceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStockPrice not implemented")
}
func (UnimplementedStockServiceServer) mustEmbedUnimplementedStockServiceServer() {}
func (UnimplementedStockServiceServer) testEmbeddedByValue()                      {}

// UnsafeStockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockServiceServer will
// result in compilation errors.
type UnsafeStockServiceServer interface {
	mustEmbedUnimplementedStockServiceServer()
}

func RegisterStockServiceServer(s grpc.ServiceRegistrar, srv StockServiceServer) {
	// If the following call panics, it indicates UnimplementedStockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StockService_ServiceDesc, srv)
}

func _StockService_GetStockList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).GetStockList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_GetStockList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).GetStockList(ctx, req.(*StockInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_AddStockPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).AddStockPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_AddStockPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).AddStockPrice(ctx, req.(*StockPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_InitStockInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitStockInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).InitStockInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_InitStockInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).InitStockInfo(ctx, req.(*InitStockInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_UpdateStockPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStockPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).UpdateStockPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_UpdateStockPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).UpdateStockPrice(ctx, req.(*UpdateStockPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StockService_ServiceDesc is the grpc.ServiceDesc for StockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stock.v1.StockService",
	HandlerType: (*StockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStockList",
			Handler:    _StockService_GetStockList_Handler,
		},
		{
			MethodName: "AddStockPrice",
			Handler:    _StockService_AddStockPrice_Handler,
		},
		{
			MethodName: "InitStockInfo",
			Handler:    _StockService_InitStockInfo_Handler,
		},
		{
			MethodName: "UpdateStockPrice",
			Handler:    _StockService_UpdateStockPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stock/v1/stock.proto",
}
