syntax = "proto3";

package stock.v1;

import "google/api/annotations.proto";

option go_package = "stock_info/api/stock/v1;v1";
option java_multiple_files = true;
option java_package = "dev.kratos.api.stock.v1";
option java_outer_classname = "StockProtoV1";

// The greeting service definition.
service StockService {
  // 查询股票列表
  rpc GetStockList(StockInfoRequest) returns (StockInfoReply) {
    option (google.api.http) = {
      post: "/api/v1/stock"
      body: "*"
    };
  }
  // 增加股票价格信息
  rpc AddStockPrice(StockPriceRequest) returns (StockPriceReply) {
    option (google.api.http) = {
      post: "/api/v1/stock/price"
      body: "*"
    };
  }
  // 初始化股票信息
  rpc InitStockInfo(InitStockInfoRequest) returns (InitStockInfoReply) {
    option (google.api.http) = {
      post: "/api/v1/stock/init"
      body: "*"
    };
  }
  // 自动更新股票价格信息
  rpc UpdateStockPrice(UpdateStockPriceRequest) returns (UpdateStockPriceReply) {
    option (google.api.http) = {
      post: "/api/v1/stock/price/update"
      body: "*"
    };
  }
  // 初始化同花顺行业、概念信息
  
}

message UpdateStockPriceRequest {}

message UpdateStockPriceReply {}

message InitStockInfoRequest {}

message InitStockInfoReply {}

message StockInfoRequest {
  string stock_code = 1;
  string stock_name = 2;
  string stock_type = 3;
  string stock_market = 4;
  int64 id = 5;
}

message StockInfoReply {
  repeated StockInfo stocks = 1;
}

message StockInfo {
  string stock_code = 1;
  string stock_name = 2;
  string stock_type = 3;
  string stock_market = 4;
}

message StockPriceRequest {
  string stock_id = 1;          // 股票代码
  string trade_date = 2;        // 交易日期
  double open_price = 3;        // 开盘价
  double close_price = 4;       // 收盘价
  double high_price = 5;        // 最高价
  double low_price = 6;         // 最低价
  int64 volume = 7;             // 成交量
  double amount = 8;            // 成交额
  double change_percent = 9;    // 涨跌幅(%)
  double margin_balance = 10;   // 融资融券余额
}

message StockPriceReply {

}