// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: stock/v1/stock.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockCode     string                 `protobuf:"bytes,1,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"`
	StockName     string                 `protobuf:"bytes,2,opt,name=stock_name,json=stockName,proto3" json:"stock_name,omitempty"`
	StockType     string                 `protobuf:"bytes,3,opt,name=stock_type,json=stockType,proto3" json:"stock_type,omitempty"`
	StockMarket   string                 `protobuf:"bytes,4,opt,name=stock_market,json=stockMarket,proto3" json:"stock_market,omitempty"`
	Id            int64                  `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockInfoRequest) Reset() {
	*x = StockInfoRequest{}
	mi := &file_stock_v1_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockInfoRequest) ProtoMessage() {}

func (x *StockInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_v1_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockInfoRequest.ProtoReflect.Descriptor instead.
func (*StockInfoRequest) Descriptor() ([]byte, []int) {
	return file_stock_v1_stock_proto_rawDescGZIP(), []int{0}
}

func (x *StockInfoRequest) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

func (x *StockInfoRequest) GetStockName() string {
	if x != nil {
		return x.StockName
	}
	return ""
}

func (x *StockInfoRequest) GetStockType() string {
	if x != nil {
		return x.StockType
	}
	return ""
}

func (x *StockInfoRequest) GetStockMarket() string {
	if x != nil {
		return x.StockMarket
	}
	return ""
}

func (x *StockInfoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StockInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stocks        []*StockInfo           `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockInfoReply) Reset() {
	*x = StockInfoReply{}
	mi := &file_stock_v1_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockInfoReply) ProtoMessage() {}

func (x *StockInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_stock_v1_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockInfoReply.ProtoReflect.Descriptor instead.
func (*StockInfoReply) Descriptor() ([]byte, []int) {
	return file_stock_v1_stock_proto_rawDescGZIP(), []int{1}
}

func (x *StockInfoReply) GetStocks() []*StockInfo {
	if x != nil {
		return x.Stocks
	}
	return nil
}

type StockInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockCode     string                 `protobuf:"bytes,1,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"`
	StockName     string                 `protobuf:"bytes,2,opt,name=stock_name,json=stockName,proto3" json:"stock_name,omitempty"`
	StockType     string                 `protobuf:"bytes,3,opt,name=stock_type,json=stockType,proto3" json:"stock_type,omitempty"`
	StockMarket   string                 `protobuf:"bytes,4,opt,name=stock_market,json=stockMarket,proto3" json:"stock_market,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockInfo) Reset() {
	*x = StockInfo{}
	mi := &file_stock_v1_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockInfo) ProtoMessage() {}

func (x *StockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stock_v1_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockInfo.ProtoReflect.Descriptor instead.
func (*StockInfo) Descriptor() ([]byte, []int) {
	return file_stock_v1_stock_proto_rawDescGZIP(), []int{2}
}

func (x *StockInfo) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

func (x *StockInfo) GetStockName() string {
	if x != nil {
		return x.StockName
	}
	return ""
}

func (x *StockInfo) GetStockType() string {
	if x != nil {
		return x.StockType
	}
	return ""
}

func (x *StockInfo) GetStockMarket() string {
	if x != nil {
		return x.StockMarket
	}
	return ""
}

type StockPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockPriceRequest) Reset() {
	*x = StockPriceRequest{}
	mi := &file_stock_v1_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockPriceRequest) ProtoMessage() {}

func (x *StockPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_v1_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockPriceRequest.ProtoReflect.Descriptor instead.
func (*StockPriceRequest) Descriptor() ([]byte, []int) {
	return file_stock_v1_stock_proto_rawDescGZIP(), []int{3}
}

type StockPriceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockPriceReply) Reset() {
	*x = StockPriceReply{}
	mi := &file_stock_v1_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockPriceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockPriceReply) ProtoMessage() {}

func (x *StockPriceReply) ProtoReflect() protoreflect.Message {
	mi := &file_stock_v1_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockPriceReply.ProtoReflect.Descriptor instead.
func (*StockPriceReply) Descriptor() ([]byte, []int) {
	return file_stock_v1_stock_proto_rawDescGZIP(), []int{4}
}

var File_stock_v1_stock_proto protoreflect.FileDescriptor

const file_stock_v1_stock_proto_rawDesc = "" +
	"\n" +
	"\x14stock/v1/stock.proto\x12\bstock.v1\x1a\x1cgoogle/api/annotations.proto\"\xa2\x01\n" +
	"\x10StockInfoRequest\x12\x1d\n" +
	"\n" +
	"stock_code\x18\x01 \x01(\tR\tstockCode\x12\x1d\n" +
	"\n" +
	"stock_name\x18\x02 \x01(\tR\tstockName\x12\x1d\n" +
	"\n" +
	"stock_type\x18\x03 \x01(\tR\tstockType\x12!\n" +
	"\fstock_market\x18\x04 \x01(\tR\vstockMarket\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\x03R\x02id\"=\n" +
	"\x0eStockInfoReply\x12+\n" +
	"\x06stocks\x18\x01 \x03(\v2\x13.stock.v1.StockInfoR\x06stocks\"\x8b\x01\n" +
	"\tStockInfo\x12\x1d\n" +
	"\n" +
	"stock_code\x18\x01 \x01(\tR\tstockCode\x12\x1d\n" +
	"\n" +
	"stock_name\x18\x02 \x01(\tR\tstockName\x12\x1d\n" +
	"\n" +
	"stock_type\x18\x03 \x01(\tR\tstockType\x12!\n" +
	"\fstock_market\x18\x04 \x01(\tR\vstockMarket\"\x13\n" +
	"\x11StockPriceRequest\"\x11\n" +
	"\x0fStockPriceReply2\xd1\x01\n" +
	"\fStockService\x12[\n" +
	"\fGetStockList\x12\x1a.stock.v1.StockInfoRequest\x1a\x18.stock.v1.StockInfoReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/api/stock\x12d\n" +
	"\rAddStockPrice\x12\x1b.stock.v1.StockPriceRequest\x1a\x19.stock.v1.StockPriceReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/stock/priceBE\n" +
	"\x17dev.kratos.api.stock.v1B\fStockProtoV1P\x01Z\x1astock_info/api/stock/v1;v1b\x06proto3"

var (
	file_stock_v1_stock_proto_rawDescOnce sync.Once
	file_stock_v1_stock_proto_rawDescData []byte
)

func file_stock_v1_stock_proto_rawDescGZIP() []byte {
	file_stock_v1_stock_proto_rawDescOnce.Do(func() {
		file_stock_v1_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stock_v1_stock_proto_rawDesc), len(file_stock_v1_stock_proto_rawDesc)))
	})
	return file_stock_v1_stock_proto_rawDescData
}

var file_stock_v1_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_stock_v1_stock_proto_goTypes = []any{
	(*StockInfoRequest)(nil),  // 0: stock.v1.StockInfoRequest
	(*StockInfoReply)(nil),    // 1: stock.v1.StockInfoReply
	(*StockInfo)(nil),         // 2: stock.v1.StockInfo
	(*StockPriceRequest)(nil), // 3: stock.v1.StockPriceRequest
	(*StockPriceReply)(nil),   // 4: stock.v1.StockPriceReply
}
var file_stock_v1_stock_proto_depIdxs = []int32{
	2, // 0: stock.v1.StockInfoReply.stocks:type_name -> stock.v1.StockInfo
	0, // 1: stock.v1.StockService.GetStockList:input_type -> stock.v1.StockInfoRequest
	3, // 2: stock.v1.StockService.AddStockPrice:input_type -> stock.v1.StockPriceRequest
	1, // 3: stock.v1.StockService.GetStockList:output_type -> stock.v1.StockInfoReply
	4, // 4: stock.v1.StockService.AddStockPrice:output_type -> stock.v1.StockPriceReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stock_v1_stock_proto_init() }
func file_stock_v1_stock_proto_init() {
	if File_stock_v1_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stock_v1_stock_proto_rawDesc), len(file_stock_v1_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stock_v1_stock_proto_goTypes,
		DependencyIndexes: file_stock_v1_stock_proto_depIdxs,
		MessageInfos:      file_stock_v1_stock_proto_msgTypes,
	}.Build()
	File_stock_v1_stock_proto = out.File
	file_stock_v1_stock_proto_goTypes = nil
	file_stock_v1_stock_proto_depIdxs = nil
}
