// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dqixuan/stock_info/configs"
	"github.com/dqixuan/stock_info/internal/dao"
	"github.com/dqixuan/stock_info/internal/data"
	"github.com/dqixuan/stock_info/internal/server"
	"github.com/dqixuan/stock_info/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(config *configs.Config, logger log.Logger) (*kratos.App, func(), error) {
	grpcServer := configs.NewGrpcCfg()
	server2 := server.NewGRPCServer(grpcServer)
	httpServer := configs.NewHttpCfg()
	mysql := configs.NewMysqlCfg()
	dataData, cleanup, err := data.NewData(mysql, logger)
	if err != nil {
		return nil, nil, err
	}
	stockDao := dao.NewStockDao(dataData)
	stockPriceDao := dao.NewStockPriceDao(dataData)
	stockService := service.NewStockService(dataData, stockDao, stockPriceDao)
	healthService := service.NewHealthService()
	server3 := server.NewHTTPServer(httpServer, stockService, healthService)
	app := newApp(logger, server2, server3)
	return app, func() {
		cleanup()
	}, nil
}
