// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dqixuan/stock_info/configs"
	"github.com/dqixuan/stock_info/internal/biz"
	"github.com/dqixuan/stock_info/internal/data"
	"github.com/dqixuan/stock_info/internal/server"
	"github.com/dqixuan/stock_info/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(config *configs.Config, logger log.Logger) (*kratos.App, func(), error) {
	grpcServer := configs.NewGrpcCfg()
	mysql := configs.NewMysqlCfg()
	dataData, cleanup, err := data.NewData(mysql, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase, config)
	server2 := server.NewGRPCServer(grpcServer, greeterService)
	httpServer := configs.NewHttpCfg()
	server3 := server.NewHTTPServer(httpServer, greeterService, logger)
	app := newApp(logger, server2, server3)
	return app, func() {
		cleanup()
	}, nil
}
