-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS stock_price (
    `ID` BIGINT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `STOCK_ID` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '股票代码',
    `TRADE_DATE` DATE NOT NULL COMMENT '交易日期',
    `OPEN_PRICE` DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT '开盘价',
    `CLOSE_PRICE` DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT '收盘价',
    `HIGH_PRICE` DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT '最高价',
    `LOW_PRICE` DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT '最低价',
    `VOLUME` BIGINT DEFAULT 0 COMMENT '成交量',
    `AMOUNT` DECIMAL(20, 2) DEFAULT 0.00 COMMENT '成交额',
    `CHANGE_PERCENT` DECIMAL(8, 4) DEFAULT 0.00 COMMENT '涨跌幅(%)',
    `MARGIN_BALANCE` DECIMAL(20, 2) DEFAULT 0.00 COMMENT '融资融券余额',
    `FINANCE_BALANCE` DECIMAL(20, 2) DEFAULT 0.00 COMMENT '融资余额',
    `FINANCE_BUY` DECIMAL(20, 2) DEFAULT 0.00 COMMENT '融资买入额',
    `FINANCE_REPAY` DECIMAL(20, 2) DEFAULT 0.00 COMMENT '融资偿还额',
    `SECURITY_LEND_VOLUME` DECIMAL(20, 2) DEFAULT 0.00 COMMENT '融券余量',
    `SECURITY_LEND_SELL` DECIMAL(20, 2) DEFAULT 0.00 COMMENT '融券卖出量',
    `SECURITY_LEND_REPAY` DECIMAL(20, 2) DEFAULT 0.00 COMMENT '融券偿还量',
    `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_stock_date (`STOCK_ID`, `TRADE_DATE`),
    KEY idx_trade_date (`TRADE_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='股票价格历史表';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS stock_prices;
-- +goose StatementEnd