-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS stocks (
    `ID` BIGINT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `STOCK_ID` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '股票代码',
    `NAME` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '股票名称',
    `SHORT_NAME` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '股票简称',
    `MARKET` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '市场(SH/SZ/BJ)',
    `STATUS` TINYINT DEFAULT 1 COMMENT '状态: 1-正常, 2ST  3*ST',
    `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY STOCK_ID (`STOCK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='股票信息表';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS stocks;
-- +goose StatementEnd
